name: Publish

on:
  # Runs on pushes targeting the default branch
  push:
    # Pattern matched against refs/tags
    tags:
      - 'v*'           # Push events to every tag not containing /

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Down scope as necessary via https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
permissions:
  checks: write
  contents: read
  packages: write
  id-token: write

jobs:
  publish:
    name: Publish NPM package
    runs-on: ubuntu-latest
    if: github.repository == 'UCLA-IRL/ndnts-aux'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Install dependencies
        run: deno install --allow-scripts
      - name: Publish package
        run:
          deno publish
